### ISSUE TITLE
[ERROR] on 'npm run build/dev'

### ISSUE THREAD

**Issue by MateuszTrN** [Prismatik/react-redux-starter#6]
Hi I have an issue with the boilerplate. I can't build it at all.

Info: 
OS: WIndows 10
NodeJS: 5.7.0
NPM: 3.10.7

npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Users\Mateusz\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.7
3 info using node@v5.7.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle react-redux-starter@2.0.4~prebuild: react-redux-starter@2.0.4
6 silly lifecycle react-redux-starter@2.0.4~prebuild: no script for prebuild, continuing
7 info lifecycle react-redux-starter@2.0.4~build: react-redux-starter@2.0.4
8 verbose lifecycle react-redux-starter@2.0.4~build: unsafe-perm in lifecycle true
9 verbose lifecycle react-redux-starter@2.0.4~build: PATH: C:\Users\Mateusz\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Mateusz\Repositories\hackzurich.timeway\node_modules.bin;C:\Program Files (x86)\iis express\PHP\v5.6;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Windows Live\Shared;C:\Users\Mateusz\AppData\Roaming\npm;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\Program Files (x86)\LINQPad5;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\system32\config\systemprofile.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\Program Files (x86)\Git\cmd;C:\Program Files\dotnet\;C:\Users\Mateusz\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\MongoDB\Server\3.2\bin
10 verbose lifecycle react-redux-starter@2.0.4~build: CWD: C:\Users\Mateusz\Repositories\hackzurich.timeway
11 silly lifecycle react-redux-starter@2.0.4~build: Args: [ '/d /s /c', 'NODE_ENV=production webpack' ]
12 silly lifecycle react-redux-starter@2.0.4~build: Returned: code: 1  signal: null
13 info lifecycle react-redux-starter@2.0.4~build: Failed to exec build script
14 verbose stack Error: react-redux-starter@2.0.4 build: `NODE_ENV=production webpack`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Mateusz\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Mateusz\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid react-redux-starter@2.0.4
16 verbose cwd C:\Users\Mateusz\Repositories\hackzurich.timeway
17 error Windows_NT 10.0.10586
18 error argv "C:\Program Files\nodejs\node.exe" "C:\Users\Mateusz\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "run" "build"
19 error node v5.7.0
20 error npm  v3.10.7
21 error code ELIFECYCLE
22 error react-redux-starter@2.0.4 build: `NODE_ENV=production webpack`
22 error Exit status 1
23 error Failed at the react-redux-starter@2.0.4 build script 'NODE_ENV=production webpack'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-redux-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     NODE_ENV=production webpack
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-redux-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-redux-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by dmmarmol** [comment]
Same issue here

**Comment by theGame** [comment]
@dmmarmol @MateuszTrN  

"dev": "NODE_ENV=development & webpack-dev-server --hot --inline",

we should use  & in between command for windows
